language: objective-c
osx_image: xcode9.2
git:
  depth: 1
branches:
  only:
    - master

cache: cocoapods

env:
  global:
    - WORKSPACE="Tapster iOS Demo.xcworkspace"
    - SCHEME="Tapster iOS Demo"
  matrix:
    - DESTINATION="OS=11.2,name=iPhone X"         LINTING="YES"
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"  LINTING="NO"
    
# Need to update the CocoaPods master repo so that PredictionIO's latest
# version can be found.
before_install:
  - pod repo update

script:
  - set -o pipefail

  # Linting with SwiftLint
  - if [ $LINTING == "YES" ]; then
      echo "SwiftLint version `swiftlint version`";
      echo "SwiftLint linting...";
      swiftlint lint --strict;
    fi

  # Build in Debug
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty
